### ISSUE TITLE
npm start 终端报错

### ISSUE THREAD

**Issue by sunchenguang** [lilongllong/netease-music-react#3]
```
ERROR in ./~/.0.4.15@iconv-lite/encodings/tables/gb18030-ranges.json
Module parse failed: F:\Github_programs\netease-music-react\node_modules\.0.4.15@iconv-lite\encodings\tables\gb18030-ranges.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:638:25)
    at Parser.parse (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:516:17)
    at Object.parse (F:\Github_programs\netease-music-react\node_modules\.3.3.0@acorn\dist\acorn.js:3098:39)
 @ ./~/.0.4.15@iconv-lite/encodings/dbcs-data.js 106:37-76
webpack: bundle is now VALID.
```
缺少某个loader吗？
另外热更新也无效，每次还要手动刷新浏览器很烦

**Comment by lilongllong** [comment]
你好，首先感谢你的支持，感谢你修改代码中不符合eslint规范的代码。
这次的错误是由于node_modules的json file 无法正确解析，需要添加json-loader，我已经添加到master分支的代码中，你可以更新下，命令: npm install。
至于热编译的问题，我会去尝试解决。

**Comment by lilongllong** [comment]
嗨:tada:,热更新已经添加，启动方式没有变

**Comment by sunchenguang** [comment]
OK
